Repository nidhipatell/WinData, pull requests merged in 2020-11, with the labels that each got.

#4 Added backend
  Iteration I/UML Diagrams/WinData_ClassDiagram.drawio
  __init__.py
  templates/index.html
Labels: enhancement

#7 Nidhi patel
  static/bridge.jpg
  static/favicon.png
  static/style.css
  templates/index.html
Labels: enhancement

#6 Added Class Diagram
  Iteration I/UML Diagrams/WinData_ClassDiagram.drawio
  Iteration I/UML Diagrams/WinData_ClassDiagram.jpg
Labels: documentation

#8 added diagrams and updated button
  Iteration I/UML Diagrams/WinData_SequenceDiagram.drawio
  Iteration I/UML Diagrams/WinData_SequenceDiagram.jpg
  Iteration I/UML Diagrams/WinData_UseCaseDiagram.drawio
  Iteration I/UML Diagrams/WinData_UseCaseDiagram.jpg
  static/style.css
Labels: documentation

#9 Niraj p
  Iteration I/UML Diagrams/WinData_SequenceDiagram.jpg
Labels: documentation

#11 update button
  Iteration I/Prototypes/Webpage_Visual.PNG
  static/style.css
  templates/index.html
Labels: enhancement

#14 New Documentation, test excel sheet and script
  Documentation/Elaboration Iteration I.pdf
  Iteration I/Prototypes/DataVisualizationPrototype.png
  Iteration I/testing/OfficialElection2010.xls
  dataVisualization.py
Labels: documentation, enhancement

#15 Nidhi patel
  static/opendata.css
  static/style.css
  static/sunset.jpg
  templates/index.html
  templates/opendata.html
Labels: enhancement
